on: [push]

jobs:
  hello_world_job:
    runs-on: [ubuntu-latest] # can't use self-hosted on action because it is public
    name: A job to say hello
    steps:

      - name: Hello world action step
        id: hello
        uses: transferwise/actions-test@v0.6.0-composite
        with:
          who-to-greet: 'Transferwise'
          dir: /

      # Use the output from the `hello` step
      - name: Get all outputs
        run: |
          echo "The time was ${{ steps.hello.outputs.time }}"
          echo "The listing was: " && echo "${{ steps.hello.outputs.listing }}"
          echo "The random id was ${{ steps.hello.outputs.random-id }}"
